a={
	100: ["When it rains"],
	200: ["Will you think of me"],
	300: ["Will you wander off into your head"],
	400: ["Shield your eyes from everything you said"],
	500: ["Would remain, when I fall asleep"],
	600: ["And wake up to someone else instead"],
	700: ["Like you were never really here, in the first place"],
	800: ["Never really here, in the first place"],
	900: ["Like you were never really here"],
	1000: ["If anything goes"],
	1100: ["If anything goes"],
	1200: ["If anything goes"],
	1300: ["If anything goes then why won't you come to me"],
	1400: ["I wrote you in prose, but you never seemed to read"],
	1500: ["Ghost in my heart and monster in the streets"],
	1600: ["I met you under a dying olive tree"],
	1700: ["I miss picking you up, wherever you are"],
	1800: ["And taking you with me wherever I want"],
	1900: ["I miss picking you up, wherever you are"],
	2000: ["And taking you with me wherever I want"],
	2100: ["When it rains"],
	2200: ["Will you think of me"],
	2300: ["Will you think of all the things you said"],
	2400: ["With your hands crossed tied around my neck"],
	2500: ["Babe the pain"],
	2600: ["The way you let me bleed out"],
	2700: ["Did I dream or was I being blind"],
	2800: ["Did I die or is this making it out alive"],
	2900: ["Did I dream or was I being blind"],
	3000: ["Did I die or is this making it out alive"],
	3100: ["I miss picking you up, wherever you are"],
	3200: ["And taking you with me wherever I want"],
	3300: ["I miss picking you up, wherever you are"],
	3400: ["And taking you with me wherever I want"]
}